title: "Shovra Das"
description: "An overview of all my repositories"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

page:
  title: "Shovra Das"

github:
  is_project_page: "true"
  repository_url: https://github.com/shovradas