title: "Shovra Das"
description: "You can find a comprehensive overview of all my repositories here"
theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme
show_downloads: "true"