remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: "Shovra Das"
description: "You can find a systematic overview of all my repositories here.<br>Please use By&lt;Category&gt; links below for a further organized view of the repositories."

sdconfig:
  profile: https://github.com/shovradas
  repositories: https://github.com/shovradas?tab=repositories