remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: "Shovra Das"
description: "A systematic overview of all my repositories. Use By&lt;Category&gt; links below at your convenience."

sdconfig:
  profile: https://github.com/shovradas
  repositories: https://github.com/shovradas?tab=repositories