remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: "Shovra Das"
description: "An overview of all my repositories"

sdconfig:
  profile: https://github.com/shovradas
  repositories: https://github.com/shovradas?tab=repositories